/*
 * Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT license.
 * See LICENSE in the project root for license information.
 */

/* global console, document, Excel, Office */

console.log("running and deployed!");

Office.onReady((info) => {
  if (info.host === Office.HostType.Excel) {
    document.getElementById("sideload-msg").style.display = "none";
    document.getElementById("app-body").style.display = "flex";
    document.getElementById("run").onclick = run;
    document.getElementById("downloadButton").onclick = download;
  }
});

export async function run() {
  try {
    await Excel.run(async (context) => {
      /**
       * Insert your Excel code here
       */
      const range = context.workbook.getSelectedRange();

      // Read the range address
      range.load("address");

      // Update the fill color
      range.format.fill.color = "blue";

      await context.sync();
      console.log(`The range address was ${range.address}.`);
    });
  } catch (error) {
    console.error(error);
  }
}

function download() {
  console.log("[Download] Starting file download process");
  console.log("User Agent:", navigator.userAgent);

  try {
    downloadSampleFile();
  } catch (error) {
    console.error("An error occurred during download:", error);
    alert("Download failed: " + error.message);
  }
}

function downloadSampleFile() {
  console.log("[Download] Generating sample file");

  try {
    // Generate sample file content
    const content = "hello world\nThis is a sample file generated by the Excel Add-in.";
    const blob = new Blob([content], { type: "text/plain;charset=utf-8;" });
    const url = URL.createObjectURL(blob);

    console.log("[Download] Blob URL created:", url);

    // Create a temporary anchor element for download
    const a = document.createElement("a");
    a.href = url;
    a.download = "sample-file.txt";
    a.style.display = "none";

    // Append to body, click, and remove
    document.body.appendChild(a);
    console.log("[Download] Triggering download via anchor element");
    a.click();

    // Clean up
    setTimeout(() => {
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      console.log("[Download] Blob URL revoked and anchor removed");
    }, 100);

    console.log("[Download] Download initiated successfully");
  } catch (error) {
    console.error("[Download] Error in downloadSampleFile:", error);
    alert("Download failed: " + error.message);
  }
}
